spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis?characterEncoding=utf-8
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  global-config:
#   db-config:
#    table-prefix:
#      id-type:



 #找视图
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /**
    #可以加载动态资源


  web:
    resources:
      static-locations: classpath:atic,classpath:/public,classpath:/resources,classpath:/META-INF/resources,/HTML,classpath:/static,classpath:static/pages/

   #加载端口号  localhost:8080
#  spring:
#    datasource:
#      druid:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/mybatis?characterEncoding=utf-8
#        username: root
#        password: root123


server:
  port: 8080
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
